blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/mcp-color-server/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🔒 Security Vulnerability
    url: mailto:security@mcp-color-server.org
    about: Report security vulnerabilities privately via email
  - name: 📚 Documentation
    url: https://github.com/your-org/mcp-color-server/tree/main/docs
    about: Browse the complete documentation
  - name: 💡 Feature Ideas
    url: https://github.com/your-org/mcp-color-server/discussions/categories/ideas
    about: Share and discuss feature ideas with the community
